name = "fastapi-mobile-app"
type = "python"
main = "worker.py"
compatibility_date = "2024-11-06"

[env.production]
zone_id = "16b85e1c695921a4d56305e4a94438e8"
account_id = "bd42b35cb77837fa4aa7df72de4f612d"

[vars]
ENVIRONMENT = "production"
